google-github-actions/deploy-cloud-functions

.github/workflows/deploy-cf-it.yml
README.md
action.yaml
tests/cleaner/cleanTestFunctions.test.ts

fix: accept region

---

.github/workflows/release-please.yml

removes job introduced in https://github.com/google-github-actions/deploy-cloud-functions/pull/10

chore: remove update-fork job

---

.github/workflows/deploy-cf-it.yml
src/main.ts

fix: Only set url output if present

---

action.yaml

Update action desc to < 125 chars for marketplace.

fix: update action desc

---

src/util.ts

fixes #26 
- throw an error if upload fails

fix: improve upload error handling

---

.github/workflows/deploy-cf-it.yml
README.md
action.yaml
src/cloudFunction.ts
src/main.ts
tests/cloudFunction.test.ts
tests/cloudFunctionClient.test.ts

feat: Add optional memory input

---

README.md

Updated example of usage for environment variables to be more clear with syntax highlighting.

Clarified env_vars usage

---

.github/workflows/deploy-cf-it.yml
src/cloudFunctionClient.ts
src/util.ts

fixes https://github.com/google-github-actions/deploy-cloud-functions/issues/41
- only resolve zip creation on `finish` event
- added more logs for insights incase of zip errors as recommended by Archiver

feat: fix zip file creation, improve logs

---

README.md
action.yaml
src/cloudFunction.ts
src/cloudFunctionClient.ts
src/main.ts
tests/cloudFunction.test.ts

* feat: add function labels support
* fix: apply changes based on code review

feat: add function labels support (#60)

---

package-lock.json
package.json

Reverts google-github-actions/deploy-cloud-functions#105

Revert "chore(deps): bump @vercel/ncc from 0.24.1 to 0.28.6"

---

src/cloudFunction.ts
tests/cloudFunction.test.ts

Fixes https://github.com/google-github-actions/deploy-cloud-functions/issues/111

Improve env var parsing behaviour

---

README.md
action.yaml
src/cloudFunction.ts
src/cloudFunctionClient.ts
src/main.ts

Expose deploy timeout as an action input

---

package.json

fixes https://github.com/google-github-actions/deploy-cloud-functions/issues/201

chore: minify dist

---

CHANGELOG.md

Update missing changelog items

---

README.md

Refs https://github.com/google-github-actions/setup-gcloud/issues/430

Pin auth to v0 and show full permissions block in examples

---

src/util.ts
tests/util.test.ts

Fixes https://github.com/google-github-actions/deploy-cloud-functions/issues/229

Handle KV values with = signs

---

.github/workflows/tag.yml
README.md

Add workflow for maintaining floating tags

---

src/client.ts

Fixes fields that are lost when updating a cloud function. References issue: https://github.com/google-github-actions/deploy-cloud-functions/issues/259

Adding missing field masks

---

.github/workflows/integration.yml
README.md
action.yaml
src/main.ts

Fixes https://github.com/google-github-actions/deploy-cloud-functions/issues/261

feat: add security_level field for https triggers

---

README.md

Closes https://github.com/google-github-actions/deploy-cloud-functions/issues/294

docs: remove note about inferring project ID

---

.github/workflows/integration.yml
.github/workflows/release.yml
.github/workflows/unit.yml
README.md

Part of https://github.com/google-github-actions/deploy-cloud-functions/issues/296

chore: clean up some Node 16 bits

---

src/util.ts

chore: fix linting error

---

README.md
action.yaml
src/main.ts
src/util.ts
tests/client.test.ts
tests/secret.test.ts
tests/util.test.ts

Fixes https://github.com/google-github-actions/deploy-cloud-functions/issues/334

bug: handle suffixes and commas in availableMemoryMb

---

README.md

I have to look this up every time I use this action. I think it's helpful to list the possible values here?

Give possible values for memory_mb

---

README.md

Spelling fix in README

---

.github/workflows/publish.yml
.github/workflows/release.yml

fix: publish and release process

---

.github/workflows/publish.yml
.github/workflows/release.yml

feat: new release process

---

.github/workflows/release.yml

fix: add bot token for release
